name: nodejs
on:
  workflow_dispatch:
jobs:
  node:
    name: Nodejs
    runs-on: [self-hosted, linux, ubuntu-18.04, ec2-ephemeral]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
