name: Provisioning tests
run-name: Provisioning tests ${{ inputs.test_dist }} ${{ inputs.test_pattern }}
on:
  workflow_dispatch:
    # inputs:
    #   test_pattern:
    #     description: "Test pattern"
    #     required: false
    #     default: "^Test_(General|Provisioning|Fleet)_.*$"
    #     type: string
    #   test_dist:
    #     description: "Distribution"
    #     required: false
    #     default: "k3s"
    #     type: choice
    #     options:
    #       - "k3s"
    #       - "rke2"
jobs:
  provisioning_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
        - test_dist: "k3s"
          test_pattern: "^Test_(General|Provisioning)_.*$"
        - test_dist: "rke2"
          test_pattern: "^Test_(General|Provisioning)_.*$"
        - test_dist: "k3s"
          test_pattern: "^Test_Operation_.*$"
        - test_dist: "rke2"
          test_pattern: "^Test_Operation_SetA_.*$"
        - test_dist: "rke2"
          test_pattern: "^Test_Operation_SetB_.*$"
        
    name: Provisioning tests 
    runs-on: [self-hosted, linux, ubuntu-18.04, ec2-ephemeral]
    steps:
      - name: Install git
        run: |
          sudo add-apt-repository ppa:git-core/candidate -y
          sudo apt update
          sudo apt install -y git
      - name: Checkout
        uses: actions/checkout@v4
      - name: testdata
        run: mkdir -p build/testdata
      - name: Install Dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > ./.dapper
          chmod +x ./.dapper
      - name: Run tests
        run: ./.dapper provisioning-tests
        env:
          V2PROV_TEST_RUN_REGEX: "${{ inputs.test_pattern }}"
          V2PROV_TEST_DIST: "${{ inputs.test_dist }}"
      - name: ls
        if: failure()
        run: ls -al build/testdata
      - name: Upload testdata
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.test_pattern }}-${{ inputs.test_dist }}-testdata
          path: |
            build/testdata/rancher.log
            build/testdata/k3s.log
            build/testdata/k3s-dump
