name: Provisioning tests
run-name: Provisioning tests ${{ inputs.test_dist }} ${{ inputs.test_pattern }}
on:
  workflow_dispatch:
    inputs:
      test_pattern:
        description: "Test pattern"
        required: false
        default: "^Test_(General|Provisioning|Fleet)_.*$"
        type: string
      test_dist:
        description: "Distribution"
        required: false
        default: "k3s"
        type: choice
        options:
          - "k3s"
          - "rke2"
jobs:
  provisioning_tests:
    strategy:
      fail-fast: false
    name: Provisioning tests 
    runs-on: [self-hosted, linux, ubuntu-18.04, ec2-ephemeral]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > ./.dapper
          chmod +x ./.dapper
      - name: Run tests
        run: ./.dapper provisioning-tests
        env:
          V2PROV_TEST_RUN_REGEX: "${{ inputs.test_pattern }}"
          V2PROV_TEST_DIST: "${{ inputs.test_dist }}"
      - name: ls
        if: always()
        run: ls -al build/testdata
      - name: Upload testdata
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.test }}-testdata
          path: |
            build/testdata/rancher.log
            build/testdata/k3s.log
            build/testdata/k3s-dump
